### ISSUE TITLE
Telly Tracker support 

### ISSUE THREAD

**Issue by ghost** [ryelogheat/xpbot#12]
Kindly add support for https://telly.wtf/ thanks for making such a good uploader soft

**Comment by ryelogheat** [comment]
Unfortunately I'm not currently apart of that site, If you know where they are currently recruiting or how to contact a staff member etc let me know via email ryelogheat@belko.pw

I'll be able to add it then :+1:

**Comment by ghost** [comment]
i am the owner 👍

**Comment by ghost** [comment]
send you invite

**Comment by ryelogheat** [comment]
Added & verified to be working (some minor quirks still but working with admin to figure them out)
