### ISSUE TITLE
Argument for Type of Content

### ISSUE THREAD

**Issue by mesoller** [ryelogheat/xpbot#18]
Sometimes the script cannot differentiate between movie and tv series. Is there any argument/flag that we can parse in the command to manually specify?

**Comment by ryelogheat** [comment]
Added (finally :smile: ) 

commit: https://github.com/ryelogheat/xpbot/commit/ef05b327214106b734ec977c0b1e1c27b7ade3a1

When running the script use the arg `-type` to specify which content you're uploading
possible types are `movie` & `tv`

full example:
`python3 auto_upload.py -t ABC -p /mnt/movies/movie.title.year.bluray.mkv -type movie -tmdb 00000 -anon`
