### ISSUE TITLE
Error while parsing nonstandard file names without season numbers

### ISSUE THREAD

**Issue by therealbungus** [ryelogheat/xpbot#22]
I have a TV show with a very uncommon naming convention (no season number, A/B/C segments) and it is erroring out when trying to parse the filenames

![Picture](https://user-images.githubusercontent.com/449237/121426315-11918380-c939-11eb-89e7-fdc572cccdd7.png)

![putty_2021-06-09_15-42-59](https://user-images.githubusercontent.com/449237/121426587-603f1d80-c939-11eb-906a-f0750d76c143.png)

**Comment by ryelogheat** [comment]
Maybe try using the `-title` arg to manually set the title?

Trying to support every possible naming style is a rabbit hole I'm not interested in going down, if [guessit](https://github.com/guessit-io/guessit) can't parse your filename, then I probably don't/won't support it either

**Comment by therealbungus** [comment]
Totally understandable, I get that this is an edge case and can just be done the old fashioned way if it fails in instances like this :)
