### ISSUE TITLE
ATH Description

### ISSUE THREAD

**Issue by rj-d2** [ryelogheat/xpbot#23]
The Description on ATH looks like this,

<a href="https://freeimage.host/i/niC9RV"><img src="https://iili.io/niC9RV.th.png" alt="niC9RV.th.png" border="0"></a>

**Comment by ryelogheat** [comment]
Should be fixed now 162697a86530ece61f3f4a5dc9d395f6ead8fafb If not then you might need to contact Aither staff & figure out what bbcode is needed for line breaks. You can edit what is used for line breaks in aither.json

**Comment by rj-d2** [comment]
its working now, thx for the fix!
