### ISSUE TITLE
Option To Mark Torrent as internal

### ISSUE THREAD

**Issue by ghost** [ryelogheat/xpbot#24]
please add Option To Mark Torrent as internal

**Comment by ryelogheat** [comment]
Should be done 33f565bc0a5c865dd01fe9cc4a312dad4428e307 

I'm not internal at any sites so I might be using outdated info/args, you'll have to try it out and let me know. This should work on all UNIT3D sites except BHD (I have no idea what internal options BHD has, they seem to have some custom stuff going on e.g. exclusivity period) 

The args you can pass are `-internal` `-freeleech` `-featured` `-doubleup` `-sticky`
