### ISSUE TITLE
check_dupes argument

### ISSUE THREAD

**Issue by rj-d2** [ryelogheat/xpbot#25]
when dupe check gets a false positive i have to edit the config.env and change check_dupes to false

would it be possible to have an argument to override check_dupes=true to false from the cli,
or can the script ask if a dupe is found to upload anyway?

love the script, thx

**Comment by ryelogheat** [comment]
ngl the dupe check function is totally half baked & could use a rewrite anyways. I can add an override option if the script is running in *interactive mode* but it gets much more tricky to do it in an automated/accurate way while following all tracker rules. 

I'll add what you described (prompt if you want to override any possible dupes) in the next day or so & will look into a better automated solution later.

**Comment by ryelogheat** [comment]
Should be fixed now https://github.com/ryelogheat/xpbot/commit/43765d9867399e5596f9697e2c414054429eb910, if a dupe is detected & you have the script in *manual mode* (`auto_mode=false`) you will now be shown a small table showing what is being detected as a dupe & a prompt asking if you want to continue the upload or cancel (See the included screenshot for an example) 

![dupes](https://user-images.githubusercontent.com/80369373/126258300-8ca7f996-b3a1-4266-8f89-721de0596e6a.png)

Also if none of the torrents onsite meet the `acceptable_similarity_percentage` then you won't be prompted & the upload will just continue like it used to 

(In the screenshot ^^ you can see 4/5 of the torrents on BHD did not meet my `acceptable_similarity_percentage` of `75%`, if all 5/5 didn't meet that requirement then I wouldn't have been prompted & the upload will finish)

**Comment by rj-d2** [comment]
thank you very much
