### ISSUE TITLE
Add support for ptpimg.me as an image host

### ISSUE THREAD

**Issue by insomniac-afk** [ryelogheat/xpbot#26]
Would it be possible to add ptpimg.me as an imagehost? I have no idea weather this is possible or not, but I thought I would request it anyway.

**Comment by ryelogheat** [comment]
Good idea & yeah its totally possible, I think I'll just utilize this existing project https://github.com/theirix/ptpimg-uploader to add support for ptpimg instead of trying to write my own solution lol

I'll find a good way to integrate it & will push some code in the next few days :+1:

**Comment by ryelogheat** [comment]
I've add support for [ptpimg](https://ptpimg.me) with this https://github.com/ryelogheat/xpbot/commit/14038890bc6c89c42c4d1a5352a9f2b760967f6f commit 

You need to install [ptpimg_uploader](https://github.com/theirix/ptpimg-uploader) using the following command:
`pip install ptpimg_uploader`

Then copy the new img_host key/vals from the newly updated `config.env.sample` https://github.com/ryelogheat/xpbot/commit/14038890bc6c89c42c4d1a5352a9f2b760967f6f#diff-c6ad8cad9a71c96650f13e29264ceade0cba01362603e2cc1e2a383e2aa250cf to your active `config.env`
<br>
Quoting [github.com/theirix/ptpimg-uploader#api-key](https://github.com/theirix/ptpimg-uploader#api-key) :
> To find your PTPImg API key, login to https://ptpimg.me, open the page source (i.e. "View->Developer->View source" menu in Chrome), find the string api_key and copy the hexademical string from the value attribute. Your API key should look like 43fe0fee-f935-4084-8a38-3e632b0be68c.

Final result example:
![ptp_host](https://user-images.githubusercontent.com/80369373/126273384-ceadbf0f-33eb-4b92-ad3d-04d9d1316c6b.png)

**Comment by ryelogheat** [comment]
Let me know if you run into any problems :+1:

**Comment by insomniac-afk** [comment]
This worked brilliantly! Even resized great, Thank you :)
