### ISSUE TITLE
i want to add my tracker..

### ISSUE THREAD

**Issue by tvserial** [ryelogheat/xpbot#29]
can you send your email or telegram?

**Comment by ryelogheat** [comment]
Sorry I'm not currently on telegram but you can instead email me at ryelogheat@pm.me I can also do discord if that's cool with you

**Comment by tvserial** [comment]
Check your email please

**Comment by ryelogheat** [comment]
I just replied to a someone who emailed me asking about adding a tracker right around when your created the issue. Not sure if that was just your alt account or someone totally else lol but here is what I told them & the same would apply to your issue.

> Just tell me the problem you're having over email & we'll figure it out that way. Also to speed the process up, can you tell me what tracker you're trying to add? also if you can get me access to that site, I can quickly write the tracker template for it myself & update the github repo for everyone to use. idk its your call.
>
> If you want to fix the issue yourself, I can help you over email. But if you don't mind inviting me to which site your trying to add, then I can probably just fix any issues myself & get the bot working with it.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by tvserial** [comment]
but im not receive any email....my site is uncutflixhd.com   ..i need to talk you

**Comment by tvserial** [comment]
![Screenshot 2021-08-29 152048](https://user-images.githubusercontent.com/54730562/131245446-6a4fcd38-69bb-4893-a7a3-2b5bb9b9fdec.jpg)
memoey error..
