### ISSUE TITLE
Season packs.

### ISSUE THREAD

**Issue by ghost** [ryelogheat/xpbot#38]
Can you fix so that the script sends Episode 0 when publishing a seasonal pack?

**Comment by ryelogheat** [comment]
Can you elaborate a bit? I'm not quite sure what you want the script to do, in a season pack upload you typically wouldn't include an episode number in the title. 

(e.g. `Some.Show.S02.1080p.WEB.etc.etc` <-- like how does **Episode 0** fit into that?)

**Comment by ghost** [comment]
Look at this issue. Same deal. UNIT3D want episodenumber 0 to be sendt as value on seasonspack.
https://github.com/ryelogheat/xpbot/issues/39

**Comment by drmboy2022** [comment]
yes same isssue
