### ISSUE TITLE
unit3d latest update broke xpbot

### ISSUE THREAD

**Issue by drmboy2022** [ryelogheat/xpbot#39]
Site response: {"success":false,"message":"Validation Error.","data":{"season_number":["The season number field is required."],"episode_number":["The episode number field is required."]}}
HTTP response status code: 404

kindly update the bot

**Comment by HDVinnie** [comment]
Pretty much `season_number` and `episode_number` are required for TV Meta categories.

CASE:
`Pope: The Most Powerful Man in History S01 1080p HMAX WEB-DL DD 2.0 H.264-TEPES ` would pass `season_number` as `1` and `episode_number` as `0`

`The Flash 2014 S08E03 720p AMZN WEB-DL DD+ 5.1 H.264-starktony`  would pass `season_number` as `8` and `episode_number` as `3`

`The Thick of It S00 Specials PAL DVD REMUX DD 2.0`  would pass `season_number` as `0` and `episode_number` as `0` as these are specials. Following TMDB standards.

This was added as it will be useful in the new torrent grouping feature and for some changes to mediahub.

XPBot already has this code in place. Just needs too be passed to the site templates. Just keep in mind `S08E03` would be passed as `season_number` as `8` and `episode_number` as `3` NOT `season_number` as `08` and `episode_number` as `03`.

@ryelogheat

**Comment by ryelogheat** [comment]
OK, working on it now. Thanks for the detailed explanation :wave:

**Comment by drmboy2022** [comment]
thanks both :)

**Comment by drmboy2022** [comment]
> OK, working on it now. Thanks for the detailed explanation 👋

i am waiting 👯 to flood my site

**Comment by HDVinnie** [comment]
> > OK, working on it now. Thanks for the detailed explanation 👋
> 
> i am waiting 👯 to flood my site

How about being patient....

**Comment by ryelogheat** [comment]
Almost done. I'm just doing some final checks to make sure its working with different content types & files

**Comment by ryelogheat** [comment]
OK the latest push should fix the issue https://github.com/ryelogheat/xpbot/commit/de607ea23dd42d8329d1337b79eda052b17b859c

Note that site_templates config files have been updated to include the following 2 new lines https://github.com/ryelogheat/xpbot/blob/de607ea23dd42d8329d1337b79eda052b17b859c/site_templates/blutopia.json#L135 https://github.com/ryelogheat/xpbot/blob/de607ea23dd42d8329d1337b79eda052b17b859c/site_templates/blutopia.json#L136
I've already updated all the site_templates/*.json files so you don't need to manually go through & add those lines, just `git pull` the entire project & you should be good to go

**Comment by ryelogheat** [comment]
If a few of you could comment & let me know if it fixed your uploading issues that would be great, until then I'll keep this issue open in case someone needs help :+1:

**Comment by drmboy2022** [comment]
just updating

**Comment by drmboy2022** [comment]
all is fine now thanks

**Comment by ghost** [comment]
Works excellent.
Thanks.
