### ISSUE TITLE
autoupload

### ISSUE THREAD

**Issue by successorliver** [ryelogheat/xpbot#52]
The auto upload script doesn't seem to be working. I tried to use if, but it doesn't even trigger (since there are no log files generated).

I followed the guide precisely; configured the auto-dl filters exactly. Edited my .rtorrent.rc present in my directory. Renamed rtorrent_on_complete_reupload.sh.sample as well as edited it. Am I missing something or is it broken?

**Comment by ryelogheat** [comment]
Can you confirm your autodl filters are working?

**Comment by ryelogheat** [comment]
imo the autodl stuff really should be its own separate project, `auto_upload.py` doesn't have any (major) unique integrations with the autodl stuff, all `rtorrent_on_complete_reupload.sh` is doing is just automatically formatting the `auto_upload.py` command

So the actual challenge here is dealing with rtorrent/autodl and getting them to pass data to a bash/python script (think of `rtorrent_on_complete_reupload.sh` as a bridge between rtorrent & `auto_upload.py`) there isn't really anything unique about it.

I honestly am not too familiar with rtorrent & the guide I put together was just shit I found online that happened to work for me, you might be better off creating your own solution

**Comment by ryelogheat** [comment]
Take the following bash "script" for example
```
#!/bin/bash

title=$1
path=$2
imdb_id=$3
upload_to=$4
time_stamp=$(date -u +"%Y-%m-%d %H:%M:%SZ")

echo "Title: $title"
echo "Path: $path"
echo "IMDB ID: $imdb_id"
echo "Upload to: $upload_to"
echo "Time stamp: $time_stamp"

echo ""
echo "python auto_upload.py -t $upload_to -p $path -imdb $imdb_id"
echo ""
```
`./example_script.sh some_title /some_movie.mkv tt00000 blu`

This takes positional args and prints them back out but you could just as easily call `auto_upload.py` or some other bot with it. So the only thing left is figuring out how to get rtorrent/autodl to basically run `./example_script.sh some_title /some_movie.mkv tt00000 blu` 

People run so many different setups/versions that I think its pointless trying to support them all or to try & create a "one solution that fits all" so its really left up to you to figure out how to get your torrent client to run the upload bot

Hope I didn't end up confusing you even more lol, let me know what you think, I might be able to offer some suggestions on solutions or answer whatever questions you have

**Comment by successorliver** [comment]
> Can you confirm your autodl filters are working?

Autodl seems to be working fine.

**Comment by successorliver** [comment]
> Hope I didn't end up confusing you even more lol, let me know what you think, I might be able to offer some suggestions on solutions or answer whatever questions you have

I'm trying my level best to understand everything since I'm pretty new to everything. I guess I'll close this issue, since things are pretty fine with the script. The only problem seems to be my setup; which in my opinion is pretty simple, but still issues arise. I'll try to tinker with some settings, and maybe update you if I get lucky.

Thank you for the script. 😃
