### ISSUE TITLE
Ability to upload Anon to sites

### ISSUE THREAD

**Issue by Vyerni** [ryelogheat/xpbot#57]
Given that anon uploading via API is capable on UNIT3D sites. Would be good to see if we can upload via anon via the script to sites.

**Comment by ryelogheat** [comment]
Already possible. See https://github.com/ryelogheat/xpbot/wiki/Args-and-User-Input#args--user-input but TL;DR use the arg `-anon` at the end of your upload command

e.g. `python3 auto_upload.py -t ABC -p /home/user/videos/file.mkv -anon`
