### ISSUE TITLE
Does not recognized DDP Atmos soundtracks

### ISSUE THREAD

**Issue by successorliver** [ryelogheat/xpbot#63]
DDP Atmos seems to not get recognized by the script

mediainfo: 

Format                                   : E-AC-3 JOC
Format/Info                              : Enhanced AC-3 with Joint Object Coding
Commercial name                          : Dolby Digital Plus with Dolby Atmos

**Comment by ryelogheat** [comment]
Fixed https://github.com/ryelogheat/xpbot/commit/476948c20b117eb5bb29bfb4f88c3984a9ebecea

Open a new issue if it still isn't working with whatever you're uploading

**Comment by successorliver** [comment]
Works so good. Thank you.
