### ISSUE TITLE
Season gets misidentified as single episode

### ISSUE THREAD

**Issue by successorliver** [ryelogheat/xpbot#64]
Season pack upload is marked as episode while uploading.

**Comment by ryelogheat** [comment]
What site is this? And could you also provide the season folder name (Replace the title & group name with something generic (e.g. "Show.Title" & "-GROUP")

**Comment by successorliver** [comment]
I tried uploading to BHD.

Show.Title.S03.2160p.HULU.WEB-DL.DDP5.1.H.265-GROUP
Show.Title.S03..1080p.HULU.WEB-DL.DDP5.1.H.264-GROUP

Each had 10 episodes.

**Comment by successorliver** [comment]
Tried to upload many other drafts. Different shows. Different release groups. Still getting sent as episode.


│ s00e00         │ S66                                                         │
│ screen_size    │ 720p                                                       │
│ source         │ Bluray                                                      │
│ source_type    │ bluray_encode                                               │
│ title          │ Show Title                                                       │
│ tmdb           │ CODE                                                      │
│ torrent_title  │ Show Title S66 720p Bluray AAC 2.0 x264-GROUP           │
│ type           │ episode

**Comment by ryelogheat** [comment]
Ah sorry I'm not on BHD anymore, they must have changed up their upload form and added some new form key/values that I'm not aware of. 

Afaik BHD has only 2 categories  (Movie or TV), did they change it recently to include "Season" or something like that?

**Comment by successorliver** [comment]
Their API overview says this, 

pack | int | The torrent TV pack flag. 1 = Must match.



pack | int | The TV pack flag for when the torrent contains a complete season. (0 = No TV pack or 1 = TV Pack). Default is 0


And yes, there are only 2 categories, Movies or TV.

**Comment by successorliver** [comment]
I did find this on the forums,

`{
    "status_code": 1,
    "page": 1,
    "results": [
	{
	"id": 10000,
	"name": "A Torrent Name",
	"folder_name": "a_folder_name",
	"info_hash": "4cdc06550732e15a9f50a22f0ceab9ae9871c7ab",
	"size": 133713371337,
	"uploaded_by": "John Doe",
	"category": "TV",
	"type": "1080p",
	"seeders": 1337,
	"leechers": 69,
	"times_completed": 4242,
	"imdb_id": "tt999333",
	"tmdb_id": "movie/333",
	"bhd_rating": 9.1,
	"tmdb_rating": 8.4,
	"imdb_rating": 7.7,
	"internal": 0,
	"tv_pack": 1,
	"promo25": 0,
	"promo50": 0,
	"promo75": 0,
	"freeleech": 0,
	"rewind": 0,
	"refund": 1,
	"limited": 0,
	"rescue": 0,
	"bumped_at": "2020-11-27 11:32:44",
	"created_at": "2020-11-27 11:32:44",
	"url": "https://beyond-hd.me/torrents/a-torrent-name.10000";,
	"download_url": "https://beyond-hd.me/torrent/download/a-torrent-name.10000/yourkeymykeysomebodyskey";; 
        }
    ],
    "total_pages" => 1,
    "total_results" => 1,
    "success" => true,
}`


It seems to use 'tv_pack'.

**Comment by ryelogheat** [comment]
Yeah its a pretty easy fix, give me a few minutes & I'll push an update

**Comment by ryelogheat** [comment]
OK try it now d31c46cf6411913cda72f2f1312ab1f43455ee3a

I had to change **2** different files (**auto_upload.py** and **site_templates/beyond-hd.json**) so make sure you get both of those updated

**Comment by successorliver** [comment]
> OK try it now [d31c46c](https://github.com/ryelogheat/xpbot/commit/d31c46cf6411913cda72f2f1312ab1f43455ee3a)
> 
> I had to change **2** different files (**auto_upload.py** and **site_templates/beyond-hd.json**) so make sure you get both of those updated

Works flawless!

**Comment by successorliver** [comment]
Another issue came into light.Any release with the format,

DAILY.SHOW.2022.06.29.NAME.OF.SPECIAL.GUEST.1080p.WEB.DD5.0.x264-GROUP.mkv

Now gets marked as TV pack.

**Comment by ryelogheat** [comment]
Fixed https://github.com/ryelogheat/xpbot/commit/9b1b5411087a888b0aedf9eda54a7416f9f5c510
